---
title: "Metodo de Biseccion en R."
output: pdf_document
date: "2022-08-30"
lang: es-ES
toc: yes
---
\newpage
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# METODO DE BISECCION EN R.
## EJEMPLO 1.  
**Calcular la raiz real de la funcion:**

$x-cos(x)=0$
```{r}
biseccion = function(f, xa, xb, tol){
if( sign(f(xa)) == sign(f(xb)) ){ stop("f(xa) y f(xb) tienen el mismo signo") }
# a = min(xa,xb)
# b = max(xa,xb)
a = xa; b = xb
k = 0
#Tabla imprimir
tabla = data.frame(k="","a"=a, "b"=b, "m"=a + 0.5*(b-a), "errorEstimado"=(b-a)/2)
repeat{
m = a + 0.5*(b-a)
if( f(m)==0 ){ cat("Cero de f en [",xa,",",xb,"] es: ", m ) }
if( sign(f(a)) != sign(f(m)) ){
b = m
} else { a = m }
dx = (b-a)/2
# cada iteraci칩n es una nueva fila en la tabla
tabla =rbind(tabla,data.frame(k="","a"=a, "b"=b, "m"=m, "errorEstimado"=dx))
k = k+1
#until
if( dx < tol ){
cat("Cero de f en [",xa,",",xb,"] es approx: ", m, "con error <=", dx,"\n")
cat("-----------------------------------------------------------------\n\n")
break;
}
} #repeat
#imprimir tabla
colnames(tabla)=c("k", "a","b", "m", "(b-a)/2^k")
print(tabla,right=F) #nombres alineados a la izquierda
}

```
 
```{r}
## Pruebas
f = function(x) x-cos(x)
curve(f, -2,2); abline(h=0, v=0) #gr치fico para decidir un intervalo
biseccion(f, 0.5, 0.8, 0.000001)
```
 
## Ejemplo 2.
```{r}
f=function(x){
  exp(3*(x-1))-log(x-1)^2+1
}
f(c(1.1,1.2,1.3,1.4,1.5,1.6,1.7))
```
```{r}

plot(f,1.1,3)
abline(h=0,v=0)
grid(5,5)
```


```{r}

curve(f,1,3,col="blue")
abline(h=0,v=0,col="red")
```


```{r}
require(pracma)
f = function(x) exp(3*(x-1))-log(x-1)^2+1
bisect(f, 1, 2,35)
```
```{r}
biseccion = function(f, xa, xb, tol){
if( sign(f(xa)) == sign(f(xb)) ){ stop("f(xa) y f(xb) tienen el mismo signo") }
# a = min(xa,xb)
# b = max(xa,xb)
a = xa; b = xb
k = 0
#Tabla imprimir
tabla = data.frame(k="","a"=a, "b"=b, "m"=a + 0.5*(b-a), "errorEstimado"=(b-a)/2)
repeat{
m = a + 0.5*(b-a)
if( f(m)==0 ){ cat("Cero de f en [",xa,",",xb,"] es: ", m ) }
if( sign(f(a)) != sign(f(m)) ){
b = m
} else { a = m }
dx = (b-a)/2
# cada iteraci칩n es una nueva fila en la tabla
tabla =rbind(tabla,data.frame(k="","a"=a, "b"=b, "m"=m, "errorEstimado"=dx))
k = k+1
#until
if( dx < tol ){
cat("Cero de f en [",xa,",",xb,"] es approx: ", m, "con error <=", dx,"\n")
cat("-----------------------------------------------------------------\n\n")
break;
}
} #repeat
#imprimir tabla
colnames(tabla)=c("k", "a","b", "m", "(b-a)/2^k")
print(tabla,right=F) #nombres alineados a la izquierda
}


```
```{r}
## Pruebas
f = function(x) exp(3*(x-1))-log(x-1)^2+1
curve(f, 1,3); abline(h=0, v=0) #gr치fico para decidir un intervalo
biseccion(f, 1.1, 2, 0.000001)

```

