---
title: "practica1"
output: pdf_document
date: '2022-07-07'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
mtcars[order(mtcars$gear,mtcars$mpg),]
```

```{r}
library(dplyr)
arrange(.data=mtcars,mtcars$gear,mtcars$mpg)
```
```{r}
small_mtcars <-
mtcars %>%
arrange(gear) %>%
slice(1:10)
small_mtcars
```
```{r}
library(ggplot2)
ggplot(mtcars, aes(x = wt, y = mpg)) +
geom_point() +
geom_smooth(method = lm)
```
```{r}
#install.packages("pacman")
library(pacman)
p_load(ggplot2, ggthemes, dplyr, readr)
```
```{r}
chilean_exports <- "year,product,export,percentage
2006,copper,4335009500,81
2006,others,1016726518,19
2007,copper,9005361914,86
2007,others,1523085299,14
2008,copper,6907056354,80
2008,others,1762684216,20
2009,copper,10529811075,81
2009,others,2464094241,19
2010,copper,14828284450,85
2010,others,2543015596,15
2011,copper,15291679086,82
2011,others,3447972354,18
2012,copper,14630686732,80
2012,others,3583968218,20
2013,copper,15244038840,79
2013,others,4051281128,21
2014,copper,14703374241,78
2014,others,4251484600,22
2015,copper,13155922363,78
2015,others,3667286912,22"
exports_data <- read_csv(chilean_exports)
```
```{r}
exports_data
```

```{r}
p1 <- ggplot(aes(y = export, x = year, colour = product), data = exports_data) +
geom_line()
p1
```
```{r}
library(reticulate)
```
```{r}
reticulate::conda_install(packages = "numpy")
```

```{python}
import numpy as np
```

```{r}
library(readxl)
CEP<-read_excel("D:/CEP_sep-oct_2017.xlsx",sheet=2)
head(CEP)

```
```{r}
library(dplyr)
CEP1=select(CEP,pond=POND,sexo=SEXO,
            region=REGION,edad=DS_P2_EXACTA,
           satisfaccion_vida=SV_1,satisfaccion_chilenos=SV_2,eval_econ=MB_P2 )
CEP1
```
```{r}
class(CEP1$sexo)
```
```{r}
table(CEP1$sexo)
```



```{r}
library(dplyr)
CEP2<-mutate(CEP1, sexo_chr = dplyr::recode(CEP1$sexo, '1' = "hombre", '2' = "mujer"))
table(CEP2$sexo_chr)
```

```{r}
CEP3 <- mutate(CEP2, sexo_factor = factor(CEP2$sexo, 
                                        labels = c("Hombre", "Mujer")))

```
```{r}
class(CEP3$sexo_factor)
```

```{r}
table(CEP3$region)
```
```{r}
library(knitr)
kable(table(CEP3$region))

```
```{r}
class(CEP3$region)
```
```{r}
library(car)
CEP <- mutate(CEP3, region_factor = car::recode(CEP3$region, "1:12 = 1; 13 = 2; 14:15 = 1"))

```
```{r}

```

```{r}
class(CEP$region_factor)
```
```{r}
library(VIM)
library(ggplot2)
head(msleep)
```

```{r}
newdata<-kNN(msleep,k=5)
head(newdata)
```

